project_id = "ozhqiraljgmbdbqamyup"

[functions.grant-admin]
verify_jwt = false

[functions.send-order-emails]
verify_jwt = false

[functions.send-tracking-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false
